import { useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import {
  locationInsertFields,
  type AnulacionPreventiva,
  type AplicacionModo,
  type AplicacionPreventiva,
  type ConcreteLocation,
  type IncidenciaPreventivaLite,
  type IntervaloUnidad,
  type PeriodicidadModo,
  type TareaPreventiva,
  type TareaPreventivaConMeses,
} from "@/lib/mantenimiento-preventivo";

const INCIDENCIA_PREVENTIVA_COLUMNS =
  "id_incidencia,id_tarea_preventiva,id_apt,id_grup,id_tipo_espacio_comun,estat,data_prevista,finalitzat_en,creado_en,id_assignat";

export type AptConActivo = {
  id_apt: number;
  id_grupo: number | null;
  nombre: string;
  activo: boolean;
};

// resolveConcreteLocations needs `activo` to expand "apartamentos activos"
// aplicaciones correctly — the shared useApartamentosLite() (used elsewhere
// for display/filtering only) doesn't select it, so this feature gets its
// own lite query rather than widening that one's shape for everyone else.
export function useApartamentosConActivoLite() {
  return useQuery({
    queryKey: ["preventivo-apts-activo"],
    queryFn: async (): Promise<AptConActivo[]> => {
      const { data, error } = await supabase
        .from("apartamentos")
        .select("id_apt,nombre,id_grupo,activo");
      if (error) throw error;
      return (data ?? []) as AptConActivo[];
    },
  });
}

export function useTareasPreventivas() {
  return useQuery({
    queryKey: ["preventivo-tareas"],
    queryFn: async (): Promise<TareaPreventiva[]> => {
      const { data, error } = await supabase.from("tareas_preventivas").select("*").order("nombre");
      if (error) throw error;
      return (data ?? []) as unknown as TareaPreventiva[];
    },
  });
}

export function useTareasPreventivasMeses() {
  return useQuery({
    queryKey: ["preventivo-meses"],
    queryFn: async (): Promise<{ id_tarea_preventiva: number; mes: number }[]> => {
      const { data, error } = await supabase
        .from("tareas_preventivas_meses")
        .select("id_tarea_preventiva,mes");
      if (error) throw error;
      return data ?? [];
    },
  });
}

export function useTareasPreventivasAplicaciones() {
  return useQuery({
    queryKey: ["preventivo-aplicaciones"],
    queryFn: async (): Promise<AplicacionPreventiva[]> => {
      const { data, error } = await supabase
        .from("tareas_preventivas_aplicaciones")
        .select(
          "id_aplicacion,id_tarea_preventiva,id_grupo,modo_aplicacion,id_tipo_espacio_comun,id_apt,creado_en",
        );
      if (error) throw error;
      return (data ?? []) as unknown as AplicacionPreventiva[];
    },
  });
}

export function useTareasPreventivasAnulaciones() {
  return useQuery({
    queryKey: ["preventivo-anulaciones"],
    queryFn: async (): Promise<AnulacionPreventiva[]> => {
      const { data, error } = await supabase
        .from("tareas_preventivas_anulaciones")
        .select(
          "id_anulacion,id_tarea_preventiva,id_grup,id_apt,id_tipo_espacio_comun,anyo,mes,definitiva,creado_en,creado_por",
        );
      if (error) throw error;
      return (data ?? []) as unknown as AnulacionPreventiva[];
    },
  });
}

// Every manteniment_incidencia ever generated by this feature — needed both
// to anchor "cada X tiempo" due dates on real closures and to render the
// planning grid's history. Small/new table for now; revisit with a date
// range filter if this ever grows large.
export function useIncidenciasPreventivas() {
  return useQuery({
    queryKey: ["preventivo-incidencias"],
    queryFn: async (): Promise<IncidenciaPreventivaLite[]> => {
      const { data, error } = await supabase
        .from("manteniment_incidencies")
        .select(INCIDENCIA_PREVENTIVA_COLUMNS)
        .not("id_tarea_preventiva", "is", null);
      if (error) throw error;
      return (data ?? []) as unknown as IncidenciaPreventivaLite[];
    },
  });
}

/** Joins tareas + meses into the shape every computation helper expects. */
export function useTareasPreventivasConMeses(): {
  data: TareaPreventivaConMeses[];
  isLoading: boolean;
  refetch: () => void;
} {
  const tareasQ = useTareasPreventivas();
  const mesesQ = useTareasPreventivasMeses();
  const data = useMemo(() => {
    const mesesByTarea = new Map<number, number[]>();
    for (const m of mesesQ.data ?? []) {
      const arr = mesesByTarea.get(m.id_tarea_preventiva) ?? [];
      arr.push(m.mes);
      mesesByTarea.set(m.id_tarea_preventiva, arr);
    }
    return (tareasQ.data ?? []).map((t) => ({
      ...t,
      meses: mesesByTarea.get(t.id_tarea_preventiva) ?? [],
    }));
  }, [tareasQ.data, mesesQ.data]);
  function refetch() {
    tareasQ.refetch();
    mesesQ.refetch();
  }
  return { data, isLoading: tareasQ.isLoading || mesesQ.isLoading, refetch };
}

export type TareaFormInput = {
  id_tarea_preventiva?: number;
  nombre: string;
  descripcion: string | null;
  modo_periodicidad: PeriodicidadModo;
  intervalo_cantidad: number | null;
  intervalo_unidad: IntervaloUnidad | null;
  meses: number[];
  aplicaciones: {
    id_grupo: number;
    modo_aplicacion: AplicacionModo;
    id_tipo_espacio_comun: number | null;
    id_apt: number | null;
  }[];
};

export type GenerarItem = {
  tarea: TareaPreventiva;
  location: ConcreteLocation;
  fechaPrevista: string;
};

export type AnularItem = {
  tarea: TareaPreventiva;
  location: ConcreteLocation;
  anyo: number;
  mes: number;
};

type AplicacionInput = {
  id_grupo: number;
  modo_aplicacion: AplicacionModo;
  id_tipo_espacio_comun: number | null;
  id_apt: number | null;
};

// Natural key matching the three partial unique indexes on
// tareas_preventivas_aplicaciones (apt_activos_uq / espacio_uq /
// apt_especifico_uq) — null is part of the key for modes that don't use a
// given column, which always store null there.
function aplicacionKey(a: AplicacionInput): string {
  const espacio = a.modo_aplicacion === "espacio_comun" ? a.id_tipo_espacio_comun : null;
  const apt = a.modo_aplicacion === "apartamento_especifico" ? a.id_apt : null;
  return `${a.id_grupo}|${a.modo_aplicacion}|${espacio}|${apt}`;
}

/**
 * Diffs the tarea's aplicaciones against the form's new set instead of a
 * blanket delete+reinsert. An aplicación keyed identically before and after
 * (same id_grupo + modo_aplicacion + id_tipo_espacio_comun) is left
 * completely untouched — its row, and crucially its `creado_en`, survives
 * the edit unchanged.
 *
 * This matters because `scopeSince` (mantenimiento-preventivo.ts) is
 * derived from each aplicación's own creado_en to guard época's vencida/
 * próxima checks against pre-existence phantoms. A wholesale replace would
 * silently reset creado_en to "now" for every aplicación on every edit —
 * even one that only renamed the tarea — making any currently-vencida
 * occurrence at those locations vanish until its next cycle, with nothing
 * actually resolved. Do not reintroduce delete+reinsert here.
 */
async function upsertAplicaciones(
  idTarea: number,
  nuevas: AplicacionInput[],
): Promise<string | null> {
  const { data: existentes, error: eSel } = await supabase
    .from("tareas_preventivas_aplicaciones")
    .select("id_aplicacion,id_grupo,modo_aplicacion,id_tipo_espacio_comun,id_apt")
    .eq("id_tarea_preventiva", idTarea);
  if (eSel) return eSel.message;

  const normalizadas = nuevas.map((a) => ({
    id_grupo: a.id_grupo,
    modo_aplicacion: a.modo_aplicacion,
    id_tipo_espacio_comun: a.modo_aplicacion === "espacio_comun" ? a.id_tipo_espacio_comun : null,
    id_apt: a.modo_aplicacion === "apartamento_especifico" ? a.id_apt : null,
  }));
  const nuevasKeys = new Set(normalizadas.map(aplicacionKey));
  const existentesByKey = new Map(
    (existentes ?? []).map((a) => [aplicacionKey(a as AplicacionInput), a.id_aplicacion]),
  );

  const idsToDelete = (existentes ?? [])
    .filter((a) => !nuevasKeys.has(aplicacionKey(a as AplicacionInput)))
    .map((a) => a.id_aplicacion);
  const aInsertar = normalizadas.filter((a) => !existentesByKey.has(aplicacionKey(a)));

  if (idsToDelete.length > 0) {
    const { error } = await supabase
      .from("tareas_preventivas_aplicaciones")
      .delete()
      .in("id_aplicacion", idsToDelete);
    if (error) return error.message;
  }
  if (aInsertar.length > 0) {
    const { error } = await supabase
      .from("tareas_preventivas_aplicaciones")
      .insert(aInsertar.map((a) => ({ id_tarea_preventiva: idTarea, ...a })));
    if (error) return error.message;
  }
  return null;
}

export function useMantenimientoPreventivoActions(onMutated?: () => void) {
  async function guardarTarea(input: TareaFormInput, creadoPor: number | null): Promise<boolean> {
    const tareaPayload = {
      nombre: input.nombre.trim(),
      descripcion: input.descripcion?.trim() || null,
      modo_periodicidad: input.modo_periodicidad,
      intervalo_cantidad: input.modo_periodicidad === "intervalo" ? input.intervalo_cantidad : null,
      intervalo_unidad: input.modo_periodicidad === "intervalo" ? input.intervalo_unidad : null,
    };

    let idTarea = input.id_tarea_preventiva ?? null;
    const isEdit = idTarea != null;

    if (idTarea == null) {
      const { data, error } = await supabase
        .from("tareas_preventivas")
        .insert({ ...tareaPayload, creado_por: creadoPor })
        .select("id_tarea_preventiva")
        .single();
      if (error) {
        toast.error("Error: " + error.message);
        return false;
      }
      idTarea = data.id_tarea_preventiva;
    } else {
      const { error } = await supabase
        .from("tareas_preventivas")
        .update(tareaPayload)
        .eq("id_tarea_preventiva", idTarea);
      if (error) {
        toast.error("Error: " + error.message);
        return false;
      }
      // Meses carry no creado_en and feed no scope calculation — a wholesale
      // replace here is harmless, unlike aplicaciones (see upsertAplicaciones).
      const { error: delMesesError } = await supabase
        .from("tareas_preventivas_meses")
        .delete()
        .eq("id_tarea_preventiva", idTarea);
      if (delMesesError) {
        toast.error("Error: " + delMesesError.message);
        return false;
      }
      const aplicError = await upsertAplicaciones(idTarea, input.aplicaciones);
      if (aplicError) {
        toast.error("Error: " + aplicError);
        return false;
      }
    }

    if (input.modo_periodicidad === "epoca_anyo" && input.meses.length > 0) {
      const { error } = await supabase
        .from("tareas_preventivas_meses")
        .insert(input.meses.map((mes) => ({ id_tarea_preventiva: idTarea!, mes })));
      if (error) {
        toast.error("Error: " + error.message);
        return false;
      }
    }

    // Edit path already handled aplicaciones above via upsertAplicaciones —
    // inserting here too would duplicate every unchanged row and violate
    // the partial unique indexes.
    if (!isEdit && input.aplicaciones.length > 0) {
      const { error } = await supabase.from("tareas_preventivas_aplicaciones").insert(
        input.aplicaciones.map((a) => ({
          id_tarea_preventiva: idTarea!,
          id_grupo: a.id_grupo,
          modo_aplicacion: a.modo_aplicacion,
          id_tipo_espacio_comun:
            a.modo_aplicacion === "espacio_comun" ? a.id_tipo_espacio_comun : null,
          id_apt: a.modo_aplicacion === "apartamento_especifico" ? a.id_apt : null,
        })),
      );
      if (error) {
        toast.error("Error: " + error.message);
        return false;
      }
    }

    toast.success("Tarea preventiva guardada");
    onMutated?.();
    return true;
  }

  /**
   * Creates a manteniment_incidencia per item (one insert statement for all
   * of them) and, when `asignarA` is given, immediately assigns every one of
   * them to that worker in a single follow-up update — "a single set of
   * writes, not one confirmation per row" per spec. Each item keeps its own
   * fecha prevista; only the assignment fields are shared across the batch.
   */
  async function generarOcurrencias(
    items: GenerarItem[],
    reporterId: number,
    asignarA?: number | null,
  ): Promise<boolean> {
    if (items.length === 0) return true;
    const payloads = items.map(({ tarea, location, fechaPrevista }) => ({
      titol: tarea.nombre,
      descripcio: tarea.descripcion,
      tipus: "manteniment" as const,
      origen: "preventiu",
      estat: "pendent_validacio" as const,
      prioritat_proposta: "normal" as const,
      id_reporter: reporterId,
      id_tarea_preventiva: tarea.id_tarea_preventiva,
      data_prevista: fechaPrevista,
      ...locationInsertFields(location),
    }));
    const { data: inserted, error } = await supabase
      .from("manteniment_incidencies")
      .insert(payloads)
      .select("id_incidencia");
    if (error) {
      toast.error("Error: " + error.message);
      return false;
    }
    const ids = (inserted ?? []).map((r) => r.id_incidencia);

    if (asignarA != null && ids.length > 0) {
      const nowIso = new Date().toISOString();
      const { error: eAsig } = await supabase
        .from("manteniment_incidencies")
        .update({
          estat: "validada",
          id_assignat: asignarA,
          // These are always generated with prioritat_proposta "normal" (see
          // the insert above) — mirror that into prioritat_confirmada here
          // the same way confirmarAsignacion always sets it alongside the
          // assignment, so a validada incidencia produced this way isn't
          // missing a field every other validada incidencia has.
          prioritat_confirmada: "normal",
          validat_per: reporterId,
          validat_en: nowIso,
          data_reprogramada_por_operario: false,
          finalitzat_en: null,
        })
        .in("id_incidencia", ids);
      if (eAsig) {
        toast.error("Se generaron pero no se pudieron asignar: " + eAsig.message);
        onMutated?.();
        return false;
      }
      // Best-effort — a notification failure must never undo the generation
      // and assignment that already succeeded above.
      try {
        const { error: notifError } = await supabase.from("mi_dia_notificaciones").insert(
          items.map((it, idx) => ({
            id_persona: asignarA,
            tipo: "mantenimiento_nueva",
            referencia_id: ids[idx],
            fecha_afectada: it.fechaPrevista,
            mensaje: `Nueva incidencia asignada: ${it.tarea.nombre}`,
          })),
        );
        if (notifError)
          console.warn("No se pudieron crear las notificaciones:", notifError.message);
      } catch (e) {
        console.warn("No se pudieron crear las notificaciones:", e);
      }
    }

    toast.success(ids.length === 1 ? "Incidencia generada" : `${ids.length} incidencias generadas`);
    onMutated?.();
    return true;
  }

  /**
   * Soft-annuls one or more "programada" occurrences (época_anyo only) —
   * inserts a tareas_preventivas_anulaciones row per item so
   * buildPlanningRow/computeEpocaPending stop computing them as due.
   * Reuses locationInsertFields() for the location columns since this
   * table's column names (id_apt/id_grup/id_tipo_espacio_comun) were
   * chosen to match it exactly.
   */
  async function anularOcurrencias(items: AnularItem[], creadoPor: number | null): Promise<boolean> {
    if (items.length === 0) return true;
    const payloads = items.map(({ tarea, location, anyo, mes }) => ({
      id_tarea_preventiva: tarea.id_tarea_preventiva,
      ...locationInsertFields(location),
      anyo,
      mes,
      creado_por: creadoPor,
    }));
    const { error } = await supabase.from("tareas_preventivas_anulaciones").insert(payloads);
    if (error) {
      toast.error("Error: " + error.message);
      return false;
    }
    toast.success(
      payloads.length === 1 ? "Ocurrencia anulada" : `${payloads.length} ocurrencias anuladas`,
    );
    onMutated?.();
    return true;
  }

  /** "Desfer" — removes the annulment record; the cell recomputes normally. */
  async function desanularOcurrencia(idAnulacion: number): Promise<boolean> {
    const { error } = await supabase
      .from("tareas_preventivas_anulaciones")
      .delete()
      .eq("id_anulacion", idAnulacion);
    if (error) {
      toast.error("Error: " + error.message);
      return false;
    }
    toast.success("Anulación deshecha");
    onMutated?.();
    return true;
  }

  /** "Anular definitivamente" — irreversible; the cell renders as empty from now on. */
  async function marcarAnulacionDefinitiva(idAnulacion: number): Promise<boolean> {
    const { error } = await supabase
      .from("tareas_preventivas_anulaciones")
      .update({ definitiva: true })
      .eq("id_anulacion", idAnulacion);
    if (error) {
      toast.error("Error: " + error.message);
      return false;
    }
    toast.success("Anulación definitiva");
    onMutated?.();
    return true;
  }

  return {
    guardarTarea,
    generarOcurrencias,
    anularOcurrencias,
    desanularOcurrencia,
    marcarAnulacionDefinitiva,
  };
}
